### ISSUE TITLE
typo in documentation INSTALLING.md

### ISSUE THREAD

**Issue by Marc12O** [Baitinq/nixos-config#10]
`$HARDWARE` -> this refers to the hardware-specific configuration (disks, kernel, boot, etc). This loads the hardware-specific configuration from /hosts/`$HOST`/default.nix

should be?

`$HARDWARE` -> this refers to the hardware-specific configuration (disks, kernel, boot, etc). This loads the hardware-specific configuration from /hardware/`$HARDWARE`/default.nix

thanks for your config by the way!

**Comment by Baitinq** [comment]
I completely missed that! Thanks :)
